### ISSUE TITLE
Support for ERC20::ERC1155 Niftyswap pool

### ISSUE THREAD

**Issue by pkieltyka** [arcadeum/niftyswap#32]
Presently, NiftyswapExchange.sol is implemented to pool/swap 1155:1155 pairs, which is very cool and useful. As discussed, it's convenient to interface with ERC20's such as having a DAI:1155 niftyswap pool or USDC:1155 pool, etc.

I propose to leave NiftyswapExchange.sol as it is (1155:1155), and write a variant as NiftyswapExchange20.sol for 20:1155 pairs, where the base currency is an ERC20 token.

**Comment by pkieltyka** [comment]
NOTE: to viewers here. We're pretty swamped so we're happy to offer a bounty for this work if you present it in a PR that is merged to master (5000 DAI). Otherwise, we'll get to it eventually as well.

**Comment by pkieltyka** [comment]
Congrats to @ScreamingHawk for winning the bounty :) and thank you for the great work at https://github.com/0xsequence/niftyswap/pull/38

**Comment by pkieltyka** [comment]
Done + merged. Going to leave this ticket open until we've performed a security audit of https://github.com/0xsequence/niftyswap/pull/38

**Comment by pkieltyka** [comment]
btw, it appears our test suite is broken in this PR.. our CI must have missed this..

```
[1]   426 passing (9m)
[1]   6 failing
[1] 
[1]   1) NiftyswapExchange20
[1]        Seperate Token Contracts
[1]          _currencyToToken() function
[1]            When trade is successful
[1]              should update the currency per token reserve:
[1] 
[1]       AssertionError: expected { Object (_hex, _isBigNumber) } to deeply equal { Object (_hex, _isBigNumber) }
[1]       + expected - actual
[1] 
[1]        {
[1]       -  "_hex": "0x10357563d481cc0000"
[1]       +  "_hex": "0x13778544706d933c77"
[1]          "_isBigNumber": true
[1]        }
[1]       
[1]       at /home/peter/Dev/0xsequence/niftyswap/tests/NiftswapExchange20.spec.ts:1686:44
[1]       at step (tests/NiftswapExchange20.spec.ts:52:23)
[1]       at Object.next (tests/NiftswapExchange20.spec.ts:33:53)
[1]       at fulfilled (tests/NiftswapExchange20.spec.ts:24:58)
[1]       at runMicrotasks (<anonymous>)
[1]       at processTicksAndRejections (internal/process/task_queues.js:95:5)
[1] 
[1]   2) NiftyswapExchange20
[1]        Seperate Token Contracts
[1]          _currencyToToken() function
[1]            When trade is successful
[1]              should have token sell price adjusted:
[1] 
[1]       AssertionError: expected { Object (_hex, _isBigNumber) } to deeply equal { Object (_hex, _isBigNumber) }
[1]       + expected - actual
[1] 
[1]        {
[1]       -  "_hex": "0x03420fe09bebc73c77"
[1]       +  "_hex": "0x04e4240e9f76de3d81"
[1]          "_isBigNumber": true
[1]        }
[1]       
[1]       at /home/peter/Dev/0xsequence/niftyswap/tests/NiftswapExchange20.spec.ts:1699:36
[1]       at step (tests/NiftswapExchange20.spec.ts:52:23)
[1]       at Object.next (tests/NiftswapExchange20.spec.ts:33:53)
[1]       at fulfilled (tests/NiftswapExchange20.spec.ts:24:58)
[1]       at runMicrotasks (<anonymous>)
[1]       at processTicksAndRejections (internal/process/task_queues.js:95:5)
[1] 
[1]   3) NiftyswapExchange20
[1]        Seperate Token Contracts
[1]          _currencyToToken() function
[1]            When trade is successful
[1]              should emit TokensPurchase event:
[1]      TypeError: Cannot read property 'topics' of undefined
[1]       at /home/peter/Dev/0xsequence/niftyswap/tests/NiftswapExchange20.spec.ts:1712:28
[1]       at step (tests/NiftswapExchange20.spec.ts:52:23)
[1]       at Object.next (tests/NiftswapExchange20.spec.ts:33:53)
[1]       at fulfilled (tests/NiftswapExchange20.spec.ts:24:58)
[1]       at runMicrotasks (<anonymous>)
[1]       at processTicksAndRejections (internal/process/task_queues.js:95:5)
[1] 
[1]   4) NiftyswapExchange20
[1]        Seperate Token Contracts (Packed)
[1]          _currencyToToken() function
[1]            When trade is successful
[1]              should update the currency per token reserve:
[1] 
[1]       AssertionError: expected { Object (_hex, _isBigNumber) } to deeply equal { Object (_hex, _isBigNumber) }
[1]       + expected - actual
[1] 
[1]        {
[1]       -  "_hex": "0x10357563d481cc0000"
[1]       +  "_hex": "0x13778544706d933c77"
[1]          "_isBigNumber": true
[1]        }
[1]       
[1]       at /home/peter/Dev/0xsequence/niftyswap/tests/NiftswapExchange20.spec.ts:1686:44
[1]       at step (tests/NiftswapExchange20.spec.ts:52:23)
[1]       at Object.next (tests/NiftswapExchange20.spec.ts:33:53)
[1]       at fulfilled (tests/NiftswapExchange20.spec.ts:24:58)
[1]       at runMicrotasks (<anonymous>)
[1]       at processTicksAndRejections (internal/process/task_queues.js:95:5)
[1] 
[1]   5) NiftyswapExchange20
[1]        Seperate Token Contracts (Packed)
[1]          _currencyToToken() function
[1]            When trade is successful
[1]              should have token sell price adjusted:
[1] 
[1]       AssertionError: expected { Object (_hex, _isBigNumber) } to deeply equal { Object (_hex, _isBigNumber) }
[1]       + expected - actual
[1] 
[1]        {
[1]       -  "_hex": "0x03420fe09bebc73c77"
[1]       +  "_hex": "0x04e4240e9f76de3d81"
[1]          "_isBigNumber": true
[1]        }
[1]       
[1]       at /home/peter/Dev/0xsequence/niftyswap/tests/NiftswapExchange20.spec.ts:1699:36
[1]       at step (tests/NiftswapExchange20.spec.ts:52:23)
[1]       at Object.next (tests/NiftswapExchange20.spec.ts:33:53)
[1]       at fulfilled (tests/NiftswapExchange20.spec.ts:24:58)
[1]       at runMicrotasks (<anonymous>)
[1]       at processTicksAndRejections (internal/process/task_queues.js:95:5)
[1] 
[1]   6) NiftyswapExchange20
[1]        Seperate Token Contracts (Packed)
[1]          _currencyToToken() function
[1]            When trade is successful
[1]              should emit TokensPurchase event:
[1]      TypeError: Cannot read property 'topics' of undefined
[1]       at /home/peter/Dev/0xsequence/niftyswap/tests/NiftswapExchange20.spec.ts:1712:28
[1]       at step (tests/NiftswapExchange20.spec.ts:52:23)
[1]       at Object.next (tests/NiftswapExchange20.spec.ts:33:53)
[1]       at fulfilled (tests/NiftswapExchange20.spec.ts:24:58)
[1]       at runMicrotasks (<anonymous>)
[1]       at processTicksAndRejections (internal/process/task_queues.js:95:5)
[1] 
[1] 
[1] 
error Command failed with exit code 6.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[1] yarn test:ganache exited with code 6
--> Sending SIGTERM to other processes..
[0] yarn start:ganache exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  niftyswap git:(master) ✗ 
```

**Comment by PhABC** [comment]
Would you mind fixing these @ScreamingHawk? Looks like these were introduced in your PR

**Comment by ScreamingHawk** [comment]
No problem. Will take a look

**Comment by ScreamingHawk** [comment]
Was missing an `await`. PR is here #43 @PhABC
